name: Auto Push to Server

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy  blog
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: check structure
        run: ls && echo "-----------" && du dist -h -d 1
      - name: copy front via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "./dist" # 直接把dist传到服务器 
          target: ${{ secrets.SERVER_TARGET }}
